POST http://localhost:8080/register/
Content-Type: application/json

{
    "username": "Tasja",
    "password": "password"
}

###
POST http://localhost:8080/token/
// Passing the clientId and clientSecret as base64 encoded in auth header
Authorization: Basic dmJmZzkwYjkwZHRmZzowaTltY2diamN2Ymo=
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=Tasja&password=password

###
POST http://localhost:8080/secure/
Authorization: Bearer 27deeccf33c6d6502aa8702692d03c533aba83e
